[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nuberu_plugin_report_generator"
version = "0.1.0"
description = "Report Generator Plugin for nuberu - generates simulation reports"
authors = [{ name = "Rubén Luque", email = "luqueruben@uniovi.es" }]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "nuberu",
]

[tool.uv.sources]
nuberu = { workspace = true }

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."nuberu"]
"custom.report_generator" = "nuberu_plugin_report_generator.plugin:ReportGeneratorPlugin"
