[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nuberu-plugin-load-balancer"
version = "0.3.0"
description = "Simple LoadBalancer plugin for nuberu"
authors = [{ name = "Ruben", email = "luqueruben@uniovi.es" }]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "nuberu",
]

[tool.uv.sources]
nuberu = { workspace = true }


[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."nuberu"]
"load_balancer.simple" = "nuberu_plugin_load_balancer.plugin:LoadBalancerPlugin"

